// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/dashboard.tsx";
import * as $3 from "./routes/login.tsx";
import * as $4 from "./routes/signup.tsx";
import * as $$0 from "./islands/AddressView.tsx";
import * as $$1 from "./islands/DashboardHeader.tsx";
import * as $$2 from "./islands/DashboardMenu.tsx";
import * as $$3 from "./islands/LogInForm.tsx";
import * as $$4 from "./islands/NightThemeSwitcher.tsx";
import * as $$5 from "./islands/SignUpForm.tsx";

const manifest = {
	routes: {
		"./routes/_404.tsx": $0,
		"./routes/_app.tsx": $1,
		"./routes/dashboard.tsx": $2,
		"./routes/login.tsx": $3,
		"./routes/signup.tsx": $4,
	},
	islands: {
		"./islands/AddressView.tsx": $$0,
		"./islands/DashboardHeader.tsx": $$1,
		"./islands/DashboardMenu.tsx": $$2,
		"./islands/LogInForm.tsx": $$3,
		"./islands/NightThemeSwitcher.tsx": $$4,
		"./islands/SignUpForm.tsx": $$5,
	},
	baseUrl: import.meta.url,
	config,
};

export default manifest;
