// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/dashboard.tsx";
import * as $2 from "./routes/login.tsx";
import * as $3 from "./routes/signup.tsx";
import * as $$0 from "./islands/AddressView.tsx";
import * as $$1 from "./islands/LogInForm.tsx";
import * as $$2 from "./islands/NightThemeSwitcher.tsx";
import * as $$3 from "./islands/SignUpForm.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/dashboard.tsx": $1,
    "./routes/login.tsx": $2,
    "./routes/signup.tsx": $3,
  },
  islands: {
    "./islands/AddressView.tsx": $$0,
    "./islands/LogInForm.tsx": $$1,
    "./islands/NightThemeSwitcher.tsx": $$2,
    "./islands/SignUpForm.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
