// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/calendar.tsx";
import * as $3 from "./routes/dashboard.tsx";
import * as $4 from "./routes/description.tsx";
import * as $5 from "./routes/faq.tsx";
import * as $6 from "./routes/login.tsx";
import * as $7 from "./routes/manager.tsx";
import * as $8 from "./routes/objects.tsx";
import * as $9 from "./routes/profile.tsx";
import * as $10 from "./routes/signup.tsx";
import * as $$0 from "./islands/AddressView.tsx";
import * as $$1 from "./islands/CalendarComponent.tsx";
import * as $$2 from "./islands/CalendarEvent.tsx";
import * as $$3 from "./islands/IconUser.tsx";
import * as $$4 from "./islands/LogInForm.tsx";
import * as $$5 from "./islands/MyProfile.tsx";
import * as $$6 from "./islands/MySetting.tsx";
import * as $$7 from "./islands/NightThemeSwitcher.tsx";
import * as $$8 from "./islands/ProgressBar.tsx";
import * as $$9 from "./islands/Security.tsx";
import * as $$10 from "./islands/SignUpForm.tsx";
import * as $$11 from "./islands/TransactionsCard.tsx";
import * as $$12 from "./islands/WalletCard.tsx";

const manifest = {
	routes: {
		"./routes/_404.tsx": $0,
		"./routes/_app.tsx": $1,
		"./routes/calendar.tsx": $2,
		"./routes/dashboard.tsx": $3,
		"./routes/description.tsx": $4,
		"./routes/faq.tsx": $5,
		"./routes/login.tsx": $6,
		"./routes/manager.tsx": $7,
		"./routes/objects.tsx": $8,
		"./routes/profile.tsx": $9,
		"./routes/signup.tsx": $10,
	},
	islands: {
		"./islands/AddressView.tsx": $$0,
		"./islands/CalendarComponent.tsx": $$1,
		"./islands/CalendarEvent.tsx": $$2,
		"./islands/IconUser.tsx": $$3,
		"./islands/LogInForm.tsx": $$4,
		"./islands/MyProfile.tsx": $$5,
		"./islands/MySetting.tsx": $$6,
		"./islands/NightThemeSwitcher.tsx": $$7,
		"./islands/ProgressBar.tsx": $$8,
		"./islands/Security.tsx": $$9,
		"./islands/SignUpForm.tsx": $$10,
		"./islands/TransactionsCard.tsx": $$11,
		"./islands/WalletCard.tsx": $$12,
	},
	baseUrl: import.meta.url,
	config,
};

export default manifest;
